import { Agent, AgentStatus, AgentType, Incident, IncidentSeverity } from './types';

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'ag-001',
    name: 'warehouse-arm-ctrl-01',
    type: AgentType.PHYSICAL,
    status: AgentStatus.RUNNING,
    project: 'Logistics Beta',
    lastActive: '2s ago',
    riskScore: 12,
    policy: 'StrictPhysical',
  },
  {
    id: 'ag-002',
    name: 'customer-support-llm-v2',
    type: AgentType.INFO,
    status: AgentStatus.RUNNING,
    project: 'CRM',
    lastActive: '100ms ago',
    riskScore: 45, // Getting high
    policy: 'StandardInfo',
  },
  {
    id: 'ag-003',
    name: 'assembly-line-visual-insp',
    type: AgentType.HYBRID,
    status: AgentStatus.PAUSED,
    project: 'Manuf. Line A',
    lastActive: '4h ago',
    riskScore: 0,
    policy: 'StrictPhysical',
  },
  {
    id: 'ag-004',
    name: 'payment-processor-agent',
    type: AgentType.INFO,
    status: AgentStatus.STOPPED,
    project: 'Finance',
    lastActive: '2d ago',
    riskScore: 98, // Why it was stopped
    policy: 'FinancialGuard',
  },
  {
    id: 'ag-005',
    name: 'drone-fleet-coordinator',
    type: AgentType.PHYSICAL,
    status: AgentStatus.QUARANTINED,
    project: 'Ext. Logistics',
    lastActive: '15m ago',
    riskScore: 88,
    policy: 'GeoFencing',
  },
  {
    id: 'ag-006',
    name: 'code-gen-assistant-internal',
    type: AgentType.INFO,
    status: AgentStatus.RUNNING,
    project: 'DevTools',
    lastActive: '1m ago',
    riskScore: 5,
    policy: 'StandardInfo',
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'inc-992',
    timestamp: '2023-10-27 14:22:10',
    agentId: 'ag-004',
    agentName: 'payment-processor-agent',
    type: 'AUTO_STOP',
    severity: IncidentSeverity.CRITICAL,
    reason: 'Unusual transaction volume detected (> $1M/sec)',
    actor: 'System (FinancialGuard)',
    resolved: false,
  },
  {
    id: 'inc-991',
    timestamp: '2023-10-27 09:15:00',
    agentId: 'ag-005',
    agentName: 'drone-fleet-coordinator',
    type: 'MANUAL_STOP',
    severity: IncidentSeverity.HIGH,
    reason: 'GPS drift detected outside safety corridor',
    actor: 'Operator (Sarah Connor)',
    resolved: true,
  },
  {
    id: 'inc-990',
    timestamp: '2023-10-26 18:40:22',
    agentId: 'ag-002',
    agentName: 'customer-support-llm-v2',
    type: 'AUTO_STOP',
    severity: IncidentSeverity.MEDIUM,
    reason: 'Rate limit exceeded (5000 req/min)',
    actor: 'System (RateLimiter)',
    resolved: true,
  },
];
